<?php

namespace Akono\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlobRepository extends EntityRepository
{
    public function getBlobs($limit = 4)
    {
        $blob = $this->createQueryBuilder('b')
                ->select('b')
                ->addOrderBy('b.id', 'ASC');

        if(false == is_null($limit))
            $blob->setMaxResults($limit);

        return $blob->getQuery()->getResult();
    }
}
