akono_site_homepage:
    path:     /
    defaults: { _controller: AkonoSiteBundle:Page:index }
    requirements:
      methods: GET
akono_site_services:
    path:     /services
    defaults: { _controller: AkonoSiteBundle:Page:services }
    requirements:
      methods: GET
akono_site_portfolio:
    path:     /portfolio
    defaults: { _controller: AkonoSiteBundle:Page:portfolio }
    requirements:
      methods: GET
akono_site_articles:
    path:     /articles
    defaults: { _controller: AkonoSiteBundle:Page:articles }
    requirements:
      methods: GET
akono_site_contact:
    path:     /contact
    defaults: { _controller: AkonoSiteBundle:Page:contact }
    requirements:
      methods: GET|POST

akono_site_service:
    path: /services/{id}
    defaults: { _controller: AkonoSiteBundle:Service:show}
    requirements:
      methods: GET
      id: \d+

akono_site_portfolio_show:
    path: /portfolio/{id}
    defaults: { _controller: AkonoSiteBundle:Portfolio:show}
    requirements:
      methods: GET
      id: \d+

akono_site_article_show:
    path: /articles/{id}
    defaults: { _controller: AkonoSiteBundle:Article:show}
    requirements:
      methods: GET
      id: \d+
